-- Criação da tabela T_Usuario
CREATE TABLE T_Usuario (
    idUsuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    dataNasc DATE NOT NULL,
    cpfCnpj VARCHAR2(14) NOT NULL UNIQUE,
    email VARCHAR2(100) NOT NULL UNIQUE,
    senha VARCHAR2(100) NOT NULL,
    telefone VARCHAR2(20) 
);

CREATE TABLE T_Usuario_PF (
    idUsuario NUMBER PRIMARY KEY,
    nr_cpf INTEGER NOT NULL,
    dt_nascimento DATE NOT NULL,
    CONSTRAINT fk_usuario_pf FOREIGN KEY (idUsuario) REFERENCES T_Usuario(idUsuario)
);

CREATE TABLE T_Usuario_PJ (
    idUsuario NUMBER PRIMARY KEY,
    nr_cnpj INTEGER NOT NULL,
    nm_fantasia VARCHAR2(50),
    CONSTRAINT fk_usuario_pj FOREIGN KEY (idUsuario) REFERENCES T_Usuario(idUsuario)
);



-- Criação da tabela T_Carteira
CREATE TABLE T_Carteira (
    idCarteira NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saldo DECIMAL(18, 2) DEFAULT 0,
    idCliente INT,
    CONSTRAINT fk_carteira_usuario FOREIGN KEY (idCliente) REFERENCES T_Usuario(idUsuario)
);

-- Criação da tabela T_Criptoativo
CREATE TABLE T_Criptoativo (
    idCriptoativo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    valorAtual DECIMAL(18, 2) NOT NULL
);

-- Criação da tabela T_Transacao
CREATE TABLE T_Transacao (
    idTransacao NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idTransacaoCarteira INT,
    idCriptoativo INT,
    valor DECIMAL(18, 2) NOT NULL,
    tipo VARCHAR(10) NOT NULL, -- pode ser compra, venda, etc.
    dataHora DATE NOT NULL,
    quantidade DECIMAL(18, 6) NOT NULL,
    CONSTRAINT fk_transacao_criptoativo FOREIGN KEY (idCriptoativo) REFERENCES T_Criptoativo(idCriptoativo)
);

-- Criação da tabela T_TransacaoCarteira
CREATE TABLE T_TransacaoCarteira (
    idTransacaoCarteira NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idTransacao INT,
    idCarteira INT,
    tipoOrigemDestino CHAR(1) NOT NULL, -- pode ser 'O' para origem e 'D' para destino
    CONSTRAINT fk_transacaocarteira_transacao FOREIGN KEY (idTransacao) REFERENCES T_Transacao(idTransacao),
    CONSTRAINT fk_transacaocarteira_carteira FOREIGN KEY (idCarteira) REFERENCES T_Carteira(idCarteira)
);

-- Criação da tabela T_Cofre
CREATE TABLE T_Cofre (
    idCofre NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idCarteira INT,
    chaveCarteira INT NOT NULL,
    CONSTRAINT fk_cofre_carteira FOREIGN KEY (idCarteira) REFERENCES T_Carteira(idCarteira)
);
